### ISSUE TITLE
Is there a way to disable ff4j swagger documentation?

### ISSUE THREAD

**Issue by adrianch** [ff4j/ff4j-spring-boot-starter-parent#339]
Hi,

I'm currently upgrading my application from the ff47 springboot starter 1.8.12 to 1.9. 
I notice ff4j swagger documentation is taking over my API documentation.

Is there a way to disable ff4j swagger documentation?

Just to let you know, my application is using springfox and from what I understand, ff4j is using springdoc.

**Comment by paul58914080** [comment]
Hello @adrianch ,

Have you tried ?

```yaml
ff4j:
  api:
    spring-doc:
      enabled: false                
```

Yes ff4j-spring-boot-starter uses springbok. Do you know which one renders the doc ? springfox or springdoc ?

[Reference](https://github.com/ff4j/ff4j-spring-boot-starter-parent/releases/tag/1.8.13)

**Comment by adrianch** [comment]
Hi @paul58914080,

Sorry, there was a typo in my original message. I meant to say upgrading from 1.8.12 to 1.9.
Unfortunately, adding that config into my yml doesn't work.
It's springdoc that renders.

This is a screenshot on 1.8.12

![ff4j_1_8_12_swagger](https://user-images.githubusercontent.com/4191551/224600786-8e3ed0a6-048d-4dfb-9224-201dfaf18646.PNG)


And this is the one from 1.18.13 or 1.9
![ff4j_swagger_1_8_13_or_later_](https://user-images.githubusercontent.com/4191551/224600834-dab5aa8c-8ec8-46aa-a53c-1d5cc8a1b166.PNG)

**Comment by paul58914080** [comment]
**Case 1**: Since you mentioned you are using springfox for your api documentation, I believe you can disable springdoc 

```yaml
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false
```
[Reference](https://springdoc.org/#disabling-the-springdoc-openapi-endpoints)

And then you can write your own SpringFox configuration to read the path that you are interested in. 

**Case 2**: If you wish to continue with springdoc, then you might ignore the path of ff4j api

```yaml
springdoc:
  paths-to-exclude: /api/ff4j
```

And then you could override the `OpenApiDefinition`. [Reference](https://springdoc.org/#adding-api-information-and-security-documentation)

**Comment by adrianch** [comment]
Thanks for the suggestions.
